services:
  postgres:
    image: postgres:18
    container_name: verifico-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: verifiko-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      REFRESH_TOKEN_DAYS: ${REFRESH_TOKEN_DAYS}
      JWT_EXPIRY: ${JWT_EXPIRY}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: dev
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_KEY: ${SMTP_KEY}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_NAME: ${SENDER_NAME}

    ports:
      - "8080:8080"

volumes:
  postgres_data:
